const $=id=>document.getElementById(id);let simulation=null,selected=0,manual=false;const first=EVENTS[0],last=EVENTS.at(-1);
const now=()=>simulation??Date.now();
const local=(t,z=8)=>new Intl.DateTimeFormat('zh-CN',{timeZone:z===7?'Asia/Jakarta':'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(t);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function state(t){let index=-1;for(let i=0;i<EVENTS.length;i++){if(EVENTS[i].at<=t)index=i;else break}return{current:index<0?null:EVENTS[index],next:EVENTS[index+1],important:EVENTS.find(e=>e.important&&e.at>t),ended:t>=last.at,index};}
function maps(list){return list.map(([name,q])=>`<a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}" target="_blank" rel="noopener noreferrer">${esc(name)} ↗</a>`).join('');}
function duration(ms){let m=Math.max(0,Math.ceil(ms/60000)),d=Math.floor(m/1440),h=Math.floor(m%1440/60);return(d?d+' 天 ':'')+(h?h+' 小时 ':'')+(m%60)+' 分钟';}
function renderDays(){const s=state(now());$('days').innerHTML=DAYS.map((d,i)=>`<button data-day="${i}" class="${i===selected?'active':''}" ${s.current?.day===i?'aria-current="date"':''} aria-label="10 月 ${i+1} 日 ${esc(d.title)}" aria-pressed="${selected===i}"><b>10.${String(i+1).padStart(2,'0')}</b><span>${esc(d.short)}</span></button>`).join('');}
function renderTimeline(){const d=DAYS[selected],s=state(now());$('dayNum').textContent=`DAY ${String(selected+1).padStart(2,'0')} / 08`;$('dayTitle').textContent=d.title;$('timezone').textContent=selected===0||selected===4?'当日涉及时区切换 · 见节点标注':d.offset===7?'爪哇当地时间 · UTC+7':'当地时间 · UTC+8';$('dayNotice').innerHTML=`<p class="notice">${esc(d.notice)}</p>`;$('timeline').innerHTML=EVENTS.filter(e=>e.day===selected).map(e=>{const current=s.current?.id===e.id;return `<article id="${e.id}" class="event ${current?'current':e.at<now()?'past':''}" ${current?'aria-current="step"':''}><div class="time">${e.time}<small>${e.date==='2026-10-09'?'10 月 9 日':(selected===0||selected===4)?(e.offset===7?'爪哇时间':'北京时间'):''}</small></div><div>${current?`<span class="badge">${simulation!==null?'模拟此刻':'按计划 · 当前'}</span>`:e.important?'<span class="badge">重要节点</span>':''}<h3>${esc(e.title)}</h3><p>${esc(e.note)}</p><div class="maps">${maps(e.maps)}</div></div></article>`}).join('');renderDays();}
function tick(full=false){const t=now(),s=state(t);if(!manual){const nextDay=s.current?.day??0;if(selected!==nextDay){selected=nextDay;full=true}}$('clock').textContent=`${simulation!==null?'模拟时间':'北京时间'} · ${local(t)}（UTC+8）`;$('mode').textContent=simulation!==null?'模拟预览':s.ended?'旅程结束':!s.current?'出发倒计时':'实时行程 · 按计划';$('currentTitle').textContent=s.current?.title??'准备出发 · 广州 → 深圳';$('currentNote').textContent=s.current?s.current.note:'10 月 1 日 07:50，从车陂启程。下方可以提前查看每天的安排。';$('currentLink').innerHTML=s.current?maps(s.current.maps.slice(0,2)):'';const n=s.important;$('nextLabel').textContent=n?'距下个重要节点':'全部行程已结束';$('countdown').textContent=n?duration(n.at-t):'已抵达';$('nextTitle').textContent=n?n.title:'广州 · 下次旅途见';$('nextTime').textContent=n?`${local(n.at,n.offset)} · ${n.offset===7?'爪哇当地时间':'当地时间 UTC+8'}`:'';if(s.next&&s.next!==n&&!s.ended){$('currentNote').textContent+=(s.current?'\n':'')+`下一步 ${s.next.time} · ${s.next.title}`;}$('live').classList.toggle('active',simulation===null&&!manual);$('status').textContent=(simulation!==null?'正在模拟时间；“回到现在”恢复实时。 ':'')+'时间表按计划推算，实际进度以现场为准；航班及船班不会自动同步。';if(full||tick.last!==s.current?.id){tick.last=s.current?.id;renderTimeline()}}
$('days').addEventListener('click',e=>{const b=e.target.closest('[data-day]');if(!b)return;selected=Number(b.dataset.day);manual=true;renderTimeline();tick();});
function jump(){const s=state(now());manual=false;selected=s.current?.day??0;renderTimeline();tick();document.getElementById(s.current?.id??first.id)?.scrollIntoView({block:'center'});}
$('live').onclick=()=>{simulation=null;manual=false;tick(true);jump()};$('jump').onclick=jump;
$('simulate').onclick=()=>{const v=$('simTime').value;if(!v){toast('请选择日期和时间');return}const t=Date.parse(v+'+08:00');if(!Number.isFinite(t)){toast('时间格式无效');return}simulation=t;manual=false;tick(true);$('simulate').closest('details').open=false;};
function toast(t){$('toast').textContent=t;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',5000);}
$('share').onclick=async()=>{const data={title:'群岛之间 · 印尼旅行助手',text:'我们的 8 天旅行：实时行程、倒计时与 Google Maps。',url:location.href.split('#')[0]};try{if(navigator.share)await navigator.share(data);else if(navigator.clipboard){await navigator.clipboard.writeText(data.url);toast('链接已复制，可以发给同行伙伴')}else prompt('复制此链接分享',data.url)}catch(e){if(e.name!=='AbortError')prompt('复制此链接分享',data.url)}};
tick(true);setInterval(()=>tick(),1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick(true)});
